name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "Kotlin Linter"
        uses: vroy/gha-kotlin-linter@v4
